### ISSUE TITLE
<class 'TypeError'>: saveNow() missing 1 required positional argument: 'callback'<class 'TypeError'>: saveNow() missing 1 required positional argument: 'callback'

### ISSUE THREAD

**Issue by xmewww** [finalion/WordQuery#102]
您好！感谢你开发出这么好的adds-on，我第一次使用anki，不知道是否是没有遗漏了设置什么步骤，无法正常使用wq功能
在添加了字典文件夹、笔记类型为basic之后，没有出现可以选择输入的field。
添加卡片时在选中正面单词右键选择all field无反应，current field报错如下
Anki 2.1.11 (3cf770c7) Python 3.6.7 Qt 5.12.1 PyQt 5.11.3
Platform: Mac 10.14.3
Flags: frz=True ao=True sv=1
Add-ons possibly involved: Word Query

Caught exception:
  File "/Users/wengxin/Library/Application Support/Anki2/addons21/775418273/prepare.py", line 45, in callback
    return func(obj)
  File "/Users/wengxin/Library/Application Support/Anki2/addons21/775418273/query.py", line 135, in query_from_editor_current_field
    editor.saveNow()
<class 'TypeError'>: saveNow() missing 1 required positional argument: 'callback'

**Comment by extendswind** [comment]
同样出现此问题，求助

> 
Anki 2.1.11 (3cf770c7) Python 3.7.3 Qt 5.12.2 PyQt 5.12.1
Platform: Linux
Flags: frz=False ao=True sv=1
Add-ons possibly involved: Word Query

**Comment by GermanniePedia** [comment]
我也有这个问题
Anki 2.1.55 (01caec2a) Python 3.9.15 Qt 6.4.0 PyQt 6.4.0 Platform: Windows-10-10.0.22623 Flags: frz=True ao=True sv=3 Add-ons, last update check: 2022-12-30 20:31:00  Caught exception: Traceback (most recent call last):   File "C:\Users\25973\AppData\Roaming\Anki2\addons21\775418273\prepare.py", line 45, in callback     return func(obj)   File "C:\Users\25973\AppData\Roaming\Anki2\addons21\775418273\query.py", line 103, in query_from_editor_all_fields     results = query_all_flds(editor.note)   File "C:\Users\25973\AppData\Roaming\Anki2\addons21\775418273\query.py", line 204, in wrap     query_func(*args, **kwargs)   File "C:\Users\25973\AppData\Roaming\Anki2\addons21\775418273\query.py", line 219, in query_all_flds     progress.update_title(u'Querying [[ %s ]]' % word)   File "C:\Users\25973\AppData\Roaming\Anki2\addons21\775418273\progress.py", line 67, in update_title     self._win.setWindowTitle(title) RuntimeError: wrapped C/C++ object of type QProgressDialog has been deleted
