### ISSUE TITLE
An error report popped up when I press the "query" button.

### ISSUE THREAD

**Issue by l2370078** [finalion/WordQuery#109]
As the title say, an error report popped up when I press the "query" button.

The following is the error report that ouccerred. 

错误 
有一个错误发生了.请在按住shift键的同时启动Anki，这样可以临时的禁用您已经安装的插件。 
如果仅仅是因为插件引起的问题，请选择工具>插件菜单项来将出错的的插件设置成失效，然后重启Anki，重复以上的步骤直到你发现了具体是哪个插件引起的问题。 
当你已经发现是因为插件引起的问题，请在我们的支持网站上 [插件支持](https://help.ankiweb.net/discussions/add-ons/) 上报告问题。 
调试信息：
Anki 2.1.29 (bbff62bf) Python 3.8.0 Qt 5.14.1 PyQt 5.14.1
Platform: Windows 10
Flags: frz=True ao=True sv=1
Add-ons, last update check: 2020-08-07 11:35:19

Caught exception:
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Roaming\Anki2\addons21\775418273\prepare.py", line 45, in callback
    return func(obj)
  File "C:\Users\Administrator\AppData\Roaming\Anki2\addons21\775418273\query.py", line 103, in query_from_editor_all_fields
    results = query_all_flds(editor.note)
  File "C:\Users\Administrator\AppData\Roaming\Anki2\addons21\775418273\query.py", line 204, in wrap
    query_func(*args, **kwargs)
  File "C:\Users\Administrator\AppData\Roaming\Anki2\addons21\775418273\query.py", line 219, in query_all_flds
    progress.update_title(u'Querying [[ %s ]]' % word)
  File "C:\Users\Administrator\AppData\Roaming\Anki2\addons21\775418273\progress.py", line 67, in update_title
    self._win.setWindowTitle(title)
RuntimeError: wrapped C/C++ object of type QProgressDialog has been deleted

**Comment by lqstc** [comment]
我也是同样的问题，楼主解决了吗？

**Comment by niyumard** [comment]
What window manager/desktop environment do you use?
