### ISSUE TITLE
Linux 下查询失败。Query failed on Linux

### ISSUE THREAD

**Issue by noyyyy** [finalion/WordQuery#110]
OS: elementary OS 5.1(based on Ubuntu 18.04)
Version: Anki 2.1.34
Plugin: Newset. Install by pasting 775418273 in Anki

### Wrong behavior 

Query failed

### When it happened

I followed the instructions, but when I click 'Query', it did not find any information by using local dictionary.

By using network dictionary, it shows that 

```
错误 
有一个错误发生了.请在按住shift键的同时启动Anki，这样可以临时的禁用您已经安装的插件。 
如果仅仅是因为插件引起的问题，请选择工具>插件菜单项来将出错的的插件设置成失效，然后重启Anki，重复以上的步骤直到你发现了具体是哪个插件引起的问题。 
当你已经发现是因为插件引起的问题，请在我们的支持网站上 [插件支持](https://help.ankiweb.net/discussions/add-ons/) 上报告问题。 
调试信息：
Anki 2.1.34 (8af8f565) Python 3.8.1 Qt 5.15.1 PyQt 5.15.1
Platform: Linux
Flags: frz=True ao=True sv=1
Add-ons, last update check: 2020-09-30 16:42:08
相关扩展:⁨Word Query⁩

Caught exception:
Traceback (most recent call last):
  File "/home/jerry/.local/share/Anki2/addons21/775418273/query.py", line 324, in run
    result = self.query(service_field, word)
  File "/home/jerry/.local/share/Anki2/addons21/775418273/query.py", line 337, in query
    return self.service.active(service_field, word)
  File "/home/jerry/.local/share/Anki2/addons21/775418273/service/base.py", line 189, in active
    result = each[1]()
  File "/home/jerry/.local/share/Anki2/addons21/775418273/service/base.py", line 69, in _deco
    res = fld_func(cls, *args, **kwargs)
  File "/home/jerry/.local/share/Anki2/addons21/775418273/service/base.py", line 317, in fld_whole
    html = self.get_html()
  File "/home/jerry/.local/share/Anki2/addons21/775418273/service/base.py", line 324, in get_html
    result = self.builder.mdx_lookup(self.word)  # self.word: unicode
  File "/home/jerry/.local/share/Anki2/addons21/775418273/libs/mdict/mdict_query.py", line 281, in mdx_lookup
    indexes = self.lookup_indexes(self._mdx_db, keyword, ignorecase)
  File "/home/jerry/.local/share/Anki2/addons21/775418273/libs/mdict/mdict_query.py", line 266, in lookup_indexes
    cursor = conn.execute(sql)
sqlite3.OperationalError: near "#333333": syntax error
```

sometimes it shows 

```
Caught exception:
Traceback (most recent call last):
  File "/home/jerry/.local/share/Anki2/addons21/775418273/prepare.py", line 45, in callback
    return func(obj)
  File "/home/jerry/.local/share/Anki2/addons21/775418273/query.py", line 103, in query_from_editor_all_fields
    results = query_all_flds(editor.note)
  File "/home/jerry/.local/share/Anki2/addons21/775418273/query.py", line 204, in wrap
    query_func(*args, **kwargs)
  File "/home/jerry/.local/share/Anki2/addons21/775418273/query.py", line 219, in query_all_flds
    progress.update_title(u'Querying [[ %s ]]' % word)
  File "/home/jerry/.local/share/Anki2/addons21/775418273/progress.py", line 67, in update_title
    self._win.setWindowTitle(title)
RuntimeError: wrapped C/C++ object of type QProgressDialog has been deleted
```

### Whether it can be reproduced

Of, course. I'd like to provide more information  if needed.

**Comment by niyumard** [comment]
What window manager/desktop environment are you using?

**Comment by noyyyy** [comment]
> What window manager/desktop environment are you using?

Sorry, I don't know what does window manager means.  I use Pantheon desktop environment, which is only used  in elementary os.

**Comment by niyumard** [comment]
That's okay. Thanks for answering. I assumed that this happens because window managers like i3wm or sway don't always offer a title bar.

I tried to fix the problem of this addon. Can you please check it and see if it works for you?
https://ankiweb.net/shared/info/1030932490

**Comment by noyyyy** [comment]
> 没关系。 谢谢回答。 我以为发生这种情况是因为i3wm或sway之类的窗口管理器并不总是提供标题栏。
> 
> 我试图解决此插件的问题。 您能否检查一下，看看它是否对您有用？
> [https://ankiweb.net/shared/info/1030932490 ](https://ankiweb.net/shared/info/1030932490)

Yes, it works for me. Thank you very much ! :heart:
