### ISSUE TITLE
不知怎样解决，需要您的帮助，谢谢啦！

### ISSUE THREAD

**Issue by zhaozihao-code** [finalion/WordQuery#111]
不知怎样解决，需要您的帮助，谢谢啦！

错误 
有一个错误发生了.请在按住shift键的同时启动Anki，这样可以临时的禁用您已经安装的插件。 
如果仅仅是因为插件引起的问题，请选择工具>插件菜单项来将出错的的插件设置成失效，然后重启Anki，重复以上的步骤直到你发现了具体是哪个插件引起的问题。 
当你已经发现是因为插件引起的问题，请在我们的支持网站上 [插件支持](https://help.ankiweb.net/discussions/add-ons/) 上报告问题。 
调试信息：
Anki 2.1.35 (84dcaa86) Python 3.8.0 Qt 5.14.2 PyQt 5.14.2
Platform: Windows 10
Flags: frz=True ao=True sv=1
Add-ons, last update check: 2020-11-21 11:36:08

wrapped C/C++ object of type QProgressDialog has been deleted
Traceback (most recent call last):
  File "C:\Users\noahpcc\AppData\Roaming\Anki2\addons21\775418273\prepare.py", line 45, in callback
    return func(obj)
  File "C:\Users\noahpcc\AppData\Roaming\Anki2\addons21\775418273\query.py", line 103, in query_from_editor_all_fields
    results = query_all_flds(editor.note)
  File "C:\Users\noahpcc\AppData\Roaming\Anki2\addons21\775418273\query.py", line 204, in wrap
    query_func(*args, **kwargs)
  File "C:\Users\noahpcc\AppData\Roaming\Anki2\addons21\775418273\query.py", line 219, in query_all_flds
    progress.update_title(u'Querying [[ %s ]]' % word)
  File "C:\Users\noahpcc\AppData\Roaming\Anki2\addons21\775418273\progress.py", line 67, in update_title
    self._win.setWindowTitle(title)
RuntimeError: wrapped C/C++ object of type QProgressDialog has been deleted

**Comment by niyumard** [comment]
What window manager/desktop environment are you using?

**Comment by GermanniePedia** [comment]
> What window manager/desktop environment are you using?

If I use Windows 11 ,the problem will remain there
