### ISSUE TITLE
不知道哪裡錯誤 請求幫忙@@

### ISSUE THREAD

**Issue by kev-chann** [finalion/WordQuery#114]
## 不知道哪裡錯誤 請求幫忙@@
Error
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed.
If the issue only occurs when add-ons are enabled, please use the Tools > Add-ons menu item to disable some add-ons and restart Anki, repeating until you discover the add-on that is causing the problem.
When you've discovered the add-on that is causing the problem, please report the issue on the add-on support site.
Debug info:
Anki 2.1.44 (b2b3275f) Python 3.8.6 Qt 5.14.2 PyQt 5.14.2
Platform: Mac 10.16
Flags: frz=True ao=True sv=2
Add-ons, last update check: 2021-07-14 21:01:41
Add-ons possibly involved: ⁨Word Query⁩

Caught exception:
Traceback (most recent call last):
  File "/Users/kevinchan/Library/Application Support/Anki2/addons21/775418273/prepare.py", line 45, in callback
    return func(obj)
  File "/Users/kevinchan/Library/Application Support/Anki2/addons21/775418273/query.py", line 103, in query_from_editor_all_fields
    results = query_all_flds(editor.note)
  File "/Users/kevinchan/Library/Application Support/Anki2/addons21/775418273/query.py", line 204, in wrap
    query_func(*args, **kwargs)
  File "/Users/kevinchan/Library/Application Support/Anki2/addons21/775418273/query.py", line 219, in query_all_flds
    progress.update_title(u'Querying [[ %s ]]' % word)
  File "/Users/kevinchan/Library/Application Support/Anki2/addons21/775418273/progress.py", line 67, in update_title
    self._win.setWindowTitle(title)
RuntimeError: wrapped C/C++ object of type QProgressDialog has been deleted

**Comment by GermanniePedia** [comment]
我也有一样的问题希望作者帮忙解决 @finalion @
