### ISSUE TITLE
UnicodeDecodeError: 'utf8' codec can't decode byte 0xc3 in position 4: unexpected end of data

### ISSUE THREAD

**Issue by ManhHungVNM** [finalion/WordQuery#27]
Hello,

After install & specify dict folder, I got error message:
```
An error occurred in an add-on.
Please post on the add-on forum:
https://anki.tenderapp.com/discussions/add-ons

Traceback (most recent call last):
  File "C:\Users\Admin\AppData\Roaming\Anki2\addons\wquery\service\manager.py", line 107, in run
    IndexBuilder(path)
  File "C:\Users\Admin\AppData\Roaming\Anki2\addons\wquery\libs\mdict\mdict_query.py", line 103, in __init__
    self._make_mdx_index(self._mdx_db)
  File "C:\Users\Admin\AppData\Roaming\Anki2\addons\wquery\libs\mdict\mdict_query.py", line 131, in _make_mdx_index
    returned_index = mdx.get_index(check_block=self._check)
  File "C:\Users\Admin\AppData\Roaming\Anki2\addons\wquery\libs\mdict\readmdict.py", line 850, in get_index
    index_dict['key_text'] = key_text.decode('utf-8')
  File "encodings\utf_8.py", line 16, in decode
UnicodeDecodeError: 'utf8' codec can't decode byte 0xc3 in position 4: unexpected end of data
Traceback (most recent call last):
  File "aqt\progress.py", line 69, in handler
  File "aqt\main.py", line 110, in setupProfile
  File "aqt\main.py", line 244, in loadProfile
  File "anki\hooks.py", line 26, in runHook
  File "C:\Users\Admin\AppData\Roaming\Anki2\addons\wordquery.py", line 20, in start_here
    wquery.start_services()
  File "C:\Users\Admin\AppData\Roaming\Anki2\addons\wquery\service\__init__.py", line 8, in start_services
    service_manager.start_all()
  File "C:\Users\Admin\AppData\Roaming\Anki2\addons\wquery\service\manager.py", line 30, in start_all
    service.index()
  File "C:\Users\Admin\AppData\Roaming\Anki2\addons\wquery\service\base.py", line 150, in index
    self.builder = IndexBuilder(self.dict_path)
  File "C:\Users\Admin\AppData\Roaming\Anki2\addons\wquery\libs\mdict\mdict_query.py", line 103, in __init__
    self._make_mdx_index(self._mdx_db)
  File "C:\Users\Admin\AppData\Roaming\Anki2\addons\wquery\libs\mdict\mdict_query.py", line 131, in _make_mdx_index
    returned_index = mdx.get_index(check_block=self._check)
  File "C:\Users\Admin\AppData\Roaming\Anki2\addons\wquery\libs\mdict\readmdict.py", line 850, in get_index
    index_dict['key_text'] = key_text.decode('utf-8')
  File "encodings\utf_8.py", line 16, in decode
UnicodeDecodeError: 'utf8' codec can't decode byte 0xc3 in position 4: unexpected end of data
```
Please tell me how to solve it!
Thank you

**Comment by finalion** [comment]
Maybe your mdx dictionary is not encoded with utf8.
You can replace "readmdict.py" (.../wquery/libs/mdict/readmdict.py) by the unziped file as follows.
[readmdict.zip](https://github.com/finalion/WordQuery/files/929211/readmdict.zip)

If it works, I will make an update for the repository.

**Comment by ManhHungVNM** [comment]
I got another error message:
```
An error occurred in an add-on.
Please post on the add-on forum:
https://anki.tenderapp.com/discussions/add-ons

Traceback (most recent call last):
  File "C:\Program Files (x86)\Anki v2.0.44\Data\addons\wquery\service\manager.py", line 107, in run
    IndexBuilder(path)
  File "C:\Program Files (x86)\Anki v2.0.44\Data\addons\wquery\libs\mdict\mdict_query.py", line 56, in __init__
    cursor = conn.execute("SELECT * FROM META WHERE key = \"version\"")
sqlite3.OperationalError: no such table: META
Traceback (most recent call last):
  File "C:\Program Files (x86)\Anki v2.0.44\Data\addons\wquery\ui.py", line 151, in show_fm_dialog
    service_manager.update_services()
  File "C:\Program Files (x86)\Anki v2.0.44\Data\addons\wquery\service\manager.py", line 36, in update_services
    self.start_all()
  File "C:\Program Files (x86)\Anki v2.0.44\Data\addons\wquery\service\manager.py", line 30, in start_all
    service.index()
  File "C:\Program Files (x86)\Anki v2.0.44\Data\addons\wquery\service\base.py", line 150, in index
    self.builder = IndexBuilder(self.dict_path)
  File "C:\Program Files (x86)\Anki v2.0.44\Data\addons\wquery\libs\mdict\mdict_query.py", line 56, in __init__
    cursor = conn.execute("SELECT * FROM META WHERE key = \"version\"")
sqlite3.OperationalError: no such table: META
```
P/S: My dictionary file is downloaded from pdawiki and works well on GoldenDict (Windows) and BlueDict (Android)

Thank you

**Comment by finalion** [comment]
Which dictionary?

**Comment by ManhHungVNM** [comment]
I have tested on some dic files: OALD9, LDOCE6, CALD3, Dictionary.com Unabridged 2016... and get same error!
In case you need a test file, I uploaded the smallest file (Dictionary.com Unabridged 2016 ~88MB at [HERE](https://drive.google.com/file/d/0B1rlVLWCKZISNXd1bjFrVDdJdDA/view?usp=sharing))
Thank you so much

**Comment by finalion** [comment]
@ManhHungVNM Your dictionary works in my anki. Is there something wrong with your filepath?

**Comment by mathsphy** [comment]
使用本地词典时，我也有和ManhHungVNM类似的问题.
使用网络词典时也会出错，我使用 有道词典 查询单词的基本释义时会报错，但是报错完后能得到基本释义。
报错信息如下：
```
Traceback (most recent call last):
  File "C:\Users\Fabrice\Documents\Anki\addons\wquery\query.py", line 51, in update_progress_label
    update_progress_label.kwargs['field_name'], number_info))
  File "C:\Users\Fabrice\Documents\Anki\addons\wquery\progress.py", line 68, in update
    self._win.setLabelText(label)
RuntimeError: wrapped C/C++ object of type QProgressDialog has been deleted
```
但如果查询字典的其他字段就会报错：
```
Traceback (most recent call last):
  File "C:\Users\Fabrice\Documents\Anki\addons\wquery\__init__.py", line 39, in callback
    return func(obj)
  File "C:\Users\Fabrice\Documents\Anki\addons\wquery\query.py", line 123, in query_from_editor_all_fields
    update_note_fields(editor.note, results)
  File "C:\Users\Fabrice\Documents\Anki\addons\wquery\query.py", line 159, in update_note_fields
    update_note_field(note, i, q)
  File "C:\Users\Fabrice\Documents\Anki\addons\wquery\query.py", line 172, in update_note_field
    note.flush()
  File "anki\notes.py", line 51, in flush
  File "anki\notes.py", line 69, in joinedFields
  File "anki\utils.py", line 265, in joinFields
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe5 in position 7861: ordinal not in range(128)

```
另外用网络词典中的法语助手查询时也会出现类似的错误...
谢谢

**Comment by marui888** [comment]
I met the similar issue too.  Python 2.7 is on my computer.
pls kindly feedback.
=========================================================
An error occurred in an add-on.
Please post on the add-on forum:
https://anki.tenderapp.com/discussions/add-ons

Traceback (most recent call last):
  File "C:\Users\OneCrazyStone\AppData\Roaming\Anki2\addons\wquery\service\manager.py", line 142, in run
    IndexBuilder(path)
  File "C:\Users\OneCrazyStone\AppData\Roaming\Anki2\addons\wquery\libs\mdict\mdict_query.py", line 103, in __init__
    self._make_mdx_index(self._mdx_db)
  File "C:\Users\OneCrazyStone\AppData\Roaming\Anki2\addons\wquery\libs\mdict\mdict_query.py", line 131, in _make_mdx_index
    returned_index = mdx.get_index(check_block=self._check)
  File "C:\Users\OneCrazyStone\AppData\Roaming\Anki2\addons\wquery\libs\mdict\readmdict.py", line 850, in get_index
    index_dict['key_text'] = key_text.decode('utf-8')
  File "encodings\utf_8.py", line 16, in decode
UnicodeDecodeError: 'utf8' codec can't decode byte 0xc3 in position 21: unexpected end of data

**Comment by finalion** [comment]
@marui888 Could you give a copy of your dictionary what this issue is happening ?  Which language?

**Comment by finalion** [comment]
@mathsphy duplicate issue #46
