### ISSUE TITLE
今天更新了最新版本就这样了，请问上一版在哪能下载吗？

### ISSUE THREAD

**Issue by Woody999** [finalion/WordQuery#29]
一个插件发生了错误。
请把它报告在插件的论坛上:
https://anki.tenderapp.com/discussions/add-ons

Traceback (most recent call last):
  File "aqt\main.py", line 165, in onOpenProfile
  File "aqt\main.py", line 244, in loadProfile
  File "anki\hooks.py", line 26, in runHook
  File "C:\Users\Administrator\AppData\Roaming\Anki2\addons\wordquery.py", line 31, in start_here
    import wquery
  File "C:\Users\Administrator\AppData\Roaming\Anki2\addons\wquery\__init__.py", line 27, in <module>
    from wquery.ui import show_options
  File "C:\Users\Administrator\AppData\Roaming\Anki2\addons\wquery\ui.py", line 34, in <module>
    from .service import service_manager
  File "C:\Users\Administrator\AppData\Roaming\Anki2\addons\wquery\service\__init__.py", line 20, in <module>
    from .manager import ServiceManager
  File "C:\Users\Administrator\AppData\Roaming\Anki2\addons\wquery\service\manager.py", line 31, in <module>
    from .base import MdxService, StardictService, WebService
  File "C:\Users\Administrator\AppData\Roaming\Anki2\addons\wquery\service\base.py", line 406
    .replace('\r\n', '<br />')
    ^
IndentationError: unexpected indent

**Comment by finalion** [comment]
你能打开这个文件看下这行代码吗？这个<br>应该不会转义啊

**Comment by GarrisonBaird** [comment]
@finalion you should add [howto get privious versions](https://github.com/finalion/WordQuery/issues/24#issuecomment-293644438) into README, along with howto report an issue

**Comment by ettucr** [comment]
作者您好,我今天依照安裝說明安裝WordQuery-master時,也是出現跟Woody999一樣的錯誤
內容如下
附加元件出現錯誤
請到附加元件的論壇上回報此問題：
https://anki.tenderapp.com/discussions/add-ons

Traceback (most recent call last):
  File "aqt\main.py", line 165, in onOpenProfile
  File "aqt\main.py", line 244, in loadProfile
  File "anki\hooks.py", line 26, in runHook
  File "C:\Users\Administrator\AppData\Roaming\Anki2\addons\wordquery.py", line 31, in start_here
    import wquery
  File "C:\Users\Administrator\AppData\Roaming\Anki2\addons\wquery\__init__.py", line 27, in <module>
    from wquery.ui import show_options
  File "C:\Users\Administrator\AppData\Roaming\Anki2\addons\wquery\ui.py", line 34, in <module>
    from .service import service_manager
  File "C:\Users\Administrator\AppData\Roaming\Anki2\addons\wquery\service\__init__.py", line 20, in <module>
    from .manager import ServiceManager
  File "C:\Users\Administrator\AppData\Roaming\Anki2\addons\wquery\service\manager.py", line 31, in <module>
    from .base import MdxService, StardictService, WebService
  File "C:\Users\Administrator\AppData\Roaming\Anki2\addons\wquery\service\base.py", line 406
    .replace('\r\n', '<br />')
    ^
IndentationError: unexpected indent

請問有什麼方法可以修復嗎?謝謝您!

**Comment by finalion** [comment]
@Woody999 @ettucr fixed.

**Comment by ettucr** [comment]
谢谢您,已经可以使用了,可以另外请问在线词典显示的内容怎麽没有海词迷你词典吗?

我的在线词典内容只有这些

百词斩
Bing
Bing xtk
西语助手
法语助手
MDX server
有道词典
有道词典-法语

**Comment by finalion** [comment]
那个不是很稳定，我删掉了，如果需要的话你从以前的提交里找到下载就行。晚上我再测一下，没问题的话我加上

**Comment by ettucr** [comment]
好的,那我找一下,谢谢您的回覆!

**Comment by thereisnowinter** [comment]
我今天也出现了这个问题

一个插件发生了错误。
请把它报告在插件的论坛上:
https://anki.tenderapp.com/discussions/add-ons

Traceback (most recent call last):
File "aqt\progress.py", line 69, in handler
File "aqt\main.py", line 110, in setupProfile
File "aqt\main.py", line 244, in loadProfile
File "anki\hooks.py", line 26, in runHook
File "C:\Users\Newman\AppData\Roaming\Anki2\addons\wordquery.py", line 31, in start_here
import wquery
File "C:\Users\Newman\AppData\Roaming\Anki2\addons\wquery\__init__.py", line 27, in <module>
from ui import show_options
File "C:\Users\Newman\AppData\Roaming\Anki2\addons\wquery\ui.py", line 34, in <module>
from wquery.service import service_manager
File "C:\Users\Newman\AppData\Roaming\Anki2\addons\wquery\service\__init__.py", line 24, in <module>
service_manager = ServiceManager()
File "C:\Users\Newman\AppData\Roaming\Anki2\addons\wquery\service\manager.py", line 36, in __init__
self.local_services = self.get_available_local_services()
File "C:\Users\Newman\AppData\Roaming\Anki2\addons\wquery\service\manager.py", line 106, in get_available_local_services
services.add(MdxService(dict_path))
File "C:\Users\Newman\AppData\Roaming\Anki2\addons\wquery\service\base.py", line 271, in __init__
self.builder.get_header()
File "C:\Users\Newman\AppData\Roaming\Anki2\addons\wquery\libs\mdict\mdict_query.py", line 69, in get_header
each[0] for each in cursor)
ValueError: need more than 2 values to unpack

**Comment by Woody999** [comment]
你是哪个版本? 我在用的是最新的版本, 没有上次的问题了.

2017-10-13 

wzh7806165 



发件人：Newman <notifications@github.com>
发送时间：2017-10-13 12:40
主题：Re: [finalion/WordQuery] 今天更新了最新版本就这样了，请问上一版在哪能下载吗？ (#29)
收件人："finalion/WordQuery"<WordQuery@noreply.github.com>
抄送："Woody999"<wzh7806165@gmail.com>,"Mention"<mention@noreply.github.com>

我今天也出现了这个问题
一个插件发生了错误。
请把它报告在插件的论坛上:
https://anki.tenderapp.com/discussions/add-ons
Traceback (most recent call last):
File "aqt\progress.py", line 69, in handler
File "aqt\main.py", line 110, in setupProfile
File "aqt\main.py", line 244, in loadProfile
File "anki\hooks.py", line 26, in runHook
File "C:\Users\Newman\AppData\Roaming\Anki2\addons\wordquery.py", line 31, in start_here
import wquery
File "C:\Users\Newman\AppData\Roaming\Anki2\addons\wquery_init_.py", line 27, in 
from ui import show_options
File "C:\Users\Newman\AppData\Roaming\Anki2\addons\wquery\ui.py", line 34, in 
from wquery.service import service_manager
File "C:\Users\Newman\AppData\Roaming\Anki2\addons\wquery\service_init_.py", line 24, in 
service_manager = ServiceManager()
File "C:\Users\Newman\AppData\Roaming\Anki2\addons\wquery\service\manager.py", line 36, in init
self.local_services = self.get_available_local_services()
File "C:\Users\Newman\AppData\Roaming\Anki2\addons\wquery\service\manager.py", line 106, in get_available_local_services
services.add(MdxService(dict_path))
File "C:\Users\Newman\AppData\Roaming\Anki2\addons\wquery\service\base.py", line 271, in init
self.builder.get_header()
File "C:\Users\Newman\AppData\Roaming\Anki2\addons\wquery\libs\mdict\mdict_query.py", line 69, in get_header
each[0] for each in cursor)
ValueError: need more than 2 values to unpack

**Comment by thereisnowinter** [comment]
我看了下,我用的是最新的版本 2.0.48.不知道为什么会有这个问题

**Comment by Woody999** [comment]
我上次遇到这个问题是更新了一下,然后就出问题了. 后来用回原来的,就没问题. 

2017-10-13 

wzh7806165 



发件人：Newman <notifications@github.com>
发送时间：2017-10-13 12:47
主题：Re: [finalion/WordQuery] 今天更新了最新版本就这样了，请问上一版在哪能下载吗？ (#29)
收件人："finalion/WordQuery"<WordQuery@noreply.github.com>
抄送："Woody999"<wzh7806165@gmail.com>,"Mention"<mention@noreply.github.com>

我看了下,我用的是最新的版本 2.0.48.不知道为什么会有这个问题

**Comment by thereisnowinter** [comment]
有可能是这个原因,我也是前两天才更新的
