### ISSUE TITLE
无法使用

### ISSUE THREAD

**Issue by voiotikos** [finalion/WordQuery#37]
打开Anki即会报错：
`Traceback (most recent call last):
  File "C:\cygwin\home\dae\win\build\pyi.win32\anki\outPYZ1.pyz/aqt.main", line 165, in onOpenProfile
  File "C:\cygwin\home\dae\win\build\pyi.win32\anki\outPYZ1.pyz/aqt.main", line 244, in loadProfile
  File "C:\cygwin\home\dae\win\build\pyi.win32\anki\outPYZ1.pyz/anki.hooks", line 26, in runHook
  File "C:\Users\ASUS\Documents\Anki\addons\wordquery.py", line 31, in start_here
    import wquery
  File "c:\pyi\iu.py", line 436, in importHook
  File "c:\pyi\iu.py", line 521, in doimport
  File "C:\Users\ASUS\Documents\Anki\addons\wquery\__init__.py", line 27, in <module>
    from wquery.ui import show_options
  File "c:\pyi\iu.py", line 436, in importHook
  File "c:\pyi\iu.py", line 521, in doimport
  File "C:\Users\ASUS\Documents\Anki\addons\wquery\ui.py", line 34, in <module>
    from .service import service_manager
  File "c:\pyi\iu.py", line 436, in importHook
  File "c:\pyi\iu.py", line 521, in doimport
  File "C:\Users\ASUS\Documents\Anki\addons\wquery\service\__init__.py", line 22, in <module>
    service_manager = ServiceManager()
  File "C:\Users\ASUS\Documents\Anki\addons\wquery\service\manager.py", line 37, in __init__
    self.web_services = self.get_available_web_services()
  File "C:\Users\ASUS\Documents\Anki\addons\wquery\service\manager.py", line 99, in get_available_web_services
    return self._get_services_from_files(WebService)
  File "C:\Users\ASUS\Documents\Anki\addons\wquery\service\manager.py", line 86, in _get_services_from_files
    '.%s' % os.path.splitext(f)[0], __package__)
  File "C:\Users\ASUS\Documents\Anki\addons\wquery\utils\importlib.py", line 30, in import_module
    raise TypeError("relative imports require the 'package' argument")
TypeError: relative imports require the 'package' argument`

我发现没有c:\pyi\这个目录，C:\cygwin这个目录在我这里也是C:\cygwin64

**Comment by finalion** [comment]
是不是改文件了？插件删除重新安装试一下

**Comment by voiotikos** [comment]
@finalion 试过了，还是这样

**Comment by finalion** [comment]
[manager.zip](https://github.com/finalion/WordQuery/files/1095862/manager.zip)
不应该啊，这个参数设置了啊。
替换这个文件，看看弹出提示内容是什么。
