### ISSUE TITLE
UnicodeEncodeErrorUnicodeEncodeError

### ISSUE THREAD

**Issue by HosseinAlipour** [finalion/WordQuery#45]
this is occurring on every word that has something like (ö,ş,ü) ...
how do I fix it?

```
An error occurred in an add-on.
Please post on the add-on forum:
https://anki.tenderapp.com/discussions/add-ons

Traceback (most recent call last):
Traceback (most recent call last):
  File "C:\Users\landlord\AppData\Roaming\Anki2\addons\wquery\query.py", line 314, in run
  File "C:\Users\landlord\AppData\Roaming\Anki2\addons\wquery\query.py", line 314, in run
        result = self.query(service_field, word)
result = self.query(service_field, word)
  File "C:\Users\landlord\AppData\Roaming\Anki2\addons\wquery\query.py", line 326, in query
  File "C:\Users\landlord\AppData\Roaming\Anki2\addons\wquery\query.py", line 326, in query
        return self.service.active(service_field, word)
return self.service.active(service_field, word)
  File "C:\Users\landlord\AppData\Roaming\Anki2\addons\wquery\service\base.py", line 201, in active
  File "C:\Users\landlord\AppData\Roaming\Anki2\addons\wquery\service\base.py", line 201, in active
        result = each[1]()
result = each[1]()
  File "C:\Users\landlord\AppData\Roaming\Anki2\addons\wquery\service\base.py", line 59, in _deco
  File "C:\Users\landlord\AppData\Roaming\Anki2\addons\wquery\service\base.py", line 59, in _deco
        res = fld_func(cls, *args, **kwargs)
res = fld_func(cls, *args, **kwargs)
  File "C:\Users\landlord\AppData\Roaming\Anki2\addons\wquery\service\base.py", line 315, in fld_whole
  File "C:\Users\landlord\AppData\Roaming\Anki2\addons\wquery\service\base.py", line 315, in fld_whole
        html = self.get_html()
html = self.get_html()
  File "C:\Users\landlord\AppData\Roaming\Anki2\addons\wquery\service\base.py", line 324, in get_html
  File "C:\Users\landlord\AppData\Roaming\Anki2\addons\wquery\service\base.py", line 324, in get_html
        result = self.builder.mdx_lookup(self.word)
result = self.builder.mdx_lookup(self.word)
  File "C:\Users\landlord\AppData\Roaming\Anki2\addons\wquery\libs\mdict\mdict_query.py", line 311, in mdx_lookup
  File "C:\Users\landlord\AppData\Roaming\Anki2\addons\wquery\libs\mdict\mdict_query.py", line 311, in mdx_lookup
        indexes = self.lookup_indexes(self._mdx_db, keyword, ignorecase)
indexes = self.lookup_indexes(self._mdx_db, keyword, ignorecase)
  File "C:\Users\landlord\AppData\Roaming\Anki2\addons\wquery\libs\mdict\mdict_query.py", line 294, in lookup_indexes
  File "C:\Users\landlord\AppData\Roaming\Anki2\addons\wquery\libs\mdict\mdict_query.py", line 294, in lookup_indexes
        keyword)
keyword)
UnicodeEncodeErrorUnicodeEncodeError: : 'ascii' codec can't encode character u'\xfc' in position 1: ordinal not in range(128)'ascii' codec can't encode character u'\xfc' in position 1: ordinal not in range(128)
```

**Comment by finalion** [comment]
@HosseinAlipour Thank you very much. This is a bug and I have fixed, please update!

**Comment by finalion** [comment]
If it is fixed, please close it.
