### ISSUE TITLE
UnicodeDecodeError: 'utf8' codec can't decode byte 0xc3 in position

### ISSUE THREAD

**Issue by HosseinAlipour** [finalion/WordQuery#46]
whenever I add a few MDX dict a traceback appear as below
should I care about this or just ignore it at all?

```
Traceback (most recent call last):
  File "C:\Users\landlord\AppData\Roaming\Anki2\addons\wquery\service\manager.py", line 142, in run
    IndexBuilder(path)
  File "C:\Users\landlord\AppData\Roaming\Anki2\addons\wquery\libs\mdict\mdict_query.py", line 105, in __init__
    self._make_mdx_index(self._mdx_db)
  File "C:\Users\landlord\AppData\Roaming\Anki2\addons\wquery\libs\mdict\mdict_query.py", line 133, in _make_mdx_index
    returned_index = mdx.get_index(check_block=self._check)
  File "C:\Users\landlord\AppData\Roaming\Anki2\addons\wquery\libs\mdict\readmdict.py", line 849, in get_index
    index_dict['key_text'] = key_text.decode('utf-8')
  File "encodings\utf_8.py", line 16, in decode
UnicodeDecodeError: 'utf8' codec can't decode byte 0xc3 in position 4: unexpected end of data 
```

**Comment by finalion** [comment]
@HosseinAlipour Can you send me a copy of your dict happening this error? I am not sure what is going on.

**Comment by HosseinAlipour** [comment]
these are what I trigger error I don't know which one exactly I added them together ...
https://drive.google.com/open?id=0B7BA9BhXUAEwbHJjSm9TODZxRHM
https://drive.google.com/open?id=0B7BA9BhXUAEwMXFlTTA3cE83bkk

**Comment by finalion** [comment]
[readmdict.zip](https://github.com/finalion/WordQuery/files/1133346/readmdict.zip)
They both work in my environment. Can you help to replace the readmict.py with this attached one?

**Comment by HosseinAlipour** [comment]
the traceback,
```
Traceback (most recent call last):
  File "C:\Users\landlord\AppData\Roaming\Anki2\addons\wquery\service\manager.py", line 142, in run
    IndexBuilder(path)
  File "C:\Users\landlord\AppData\Roaming\Anki2\addons\wquery\libs\mdict\mdict_query.py", line 105, in __init__
    self._make_mdx_index(self._mdx_db)
  File "C:\Users\landlord\AppData\Roaming\Anki2\addons\wquery\libs\mdict\mdict_query.py", line 133, in _make_mdx_index
    returned_index = mdx.get_index(check_block=self._check)
  File "C:\Users\landlord\AppData\Roaming\Anki2\addons\wquery\libs\mdict\readmdict.py", line 849, in get_index
    index_dict['key_text'] = key_text.decode('utf-8')
  File "encodings\utf_8.py", line 16, in decode
UnicodeDecodeError: 'utf8' codec can't decode byte 0xc3 in position 4: unexpected end of data
```

you can join me by team viewer if it helps

**Comment by finalion** [comment]
You didn't replace the file rightly.  https://github.com/finalion/WordQuery/files/1133346/readmdict.zip

**Comment by HosseinAlipour** [comment]
actually, I forgot to restart anki! and it Fixed the issue!
TYVM

**Comment by finalion** [comment]
But it's a very coarse solution and I don't know why it happens.

**Comment by finalion** [comment]
Can you tell me what word you are querying in these dicts?

**Comment by HosseinAlipour** [comment]
Turkish to the English definition and in a bunch of other MDX files English to Persian and Persian to English that was triggering this error when adding them... 
I removed all *.db files and added them again, no error appeared. I Think it got fixed.
