### ISSUE TITLE
选择字典文件夹确定后弹出报告

### ISSUE THREAD

**Issue by wulanghao** [finalion/WordQuery#55]
###你好
### 一个插件发生了错误。
请把它报告在插件的论坛上:
https://anki.tenderapp.com/discussions/add-ons

Traceback (most recent call last):
  File "C:\Users\haola\AppData\Roaming\Anki2\addons\wquery\ui.py", line 189, in show_fm_dialog
    service_manager.update_services()
  File "C:\Users\haola\AppData\Roaming\Anki2\addons\wquery\service\manager.py", line 51, in update_services
    self.local_services = self.get_available_local_services()
  File "C:\Users\haola\AppData\Roaming\Anki2\addons\wquery\service\manager.py", line 106, in get_available_local_services
    services.add(MdxService(dict_path))
  File "C:\Users\haola\AppData\Roaming\Anki2\addons\wquery\service\base.py", line 271, in __init__
    self.builder.get_header()
  File "C:\Users\haola\AppData\Roaming\Anki2\addons\wquery\libs\mdict\mdict_query.py", line 69, in get_header
    each[0] for each in cursor)
ValueError: need more than 2 values to unpack

**Comment by finalion** [comment]
plz try.
