### ISSUE TITLE
文件占用

### ISSUE THREAD

**Issue by TheKiteRunning** [finalion/WordQuery#58]
感谢!
### Wrong behavior 
An error occurred in an add-on.
Please post on the add-on forum:
https://anki.tenderapp.com/discussions/add-ons

Traceback (most recent call last):
  File "C:\Users\123\AppData\Roaming\Anki2\addons\wquery\query.py", line 320, in run
    result = self.query(service_field, word)
  File "C:\Users\123\AppData\Roaming\Anki2\addons\wquery\query.py", line 333, in query
    return self.service.active(service_field, word)
  File "C:\Users\123\AppData\Roaming\Anki2\addons\wquery\service\base.py", line 173, in active
    result = each[1]()
  File "C:\Users\123\AppData\Roaming\Anki2\addons\wquery\service\base.py", line 58, in _deco
    res = fld_func(cls, *args, **kwargs)
  File "C:\Users\123\AppData\Roaming\Anki2\addons\wquery\service\baicizhan.py", line 44, in fld_phonetic
    os.remove(audio_name)

**WindowsError: [Error 32] The process cannot access the file because it is being used by another process: u'bcz_Demosthenes.mp3'**

### When it happened
使用百词斩查音频批量查词，提示文件占用，按下close之后又会自动继续查找；但不按cloze就会停在那里。

尝试把collectionmedia里面的bcz音频都删掉，检查音频后重查，问题依旧。
### Whether it can be reproduced
不知道肿么讲，用的是github的最新版

**Comment by finalion** [comment]
This is a bug, thanks. Please try.

**Comment by TheKiteRunning** [comment]
Now it works well. Thank you for your effective work and prompt help!

The Fields showed in the following dialog seems repeat in function with Words. How do you find if chaning it to be Percent (Queryed/Total).

By the way, is there anyway to add a tag for those queryed words, since sometimes wordquery failed to work, and it is diffcult to locate the unqueryed words.
 
![image](https://user-images.githubusercontent.com/24802332/29999954-429fdd8e-908d-11e7-96e3-faa67b095c19.png)
