### ISSUE TITLE
出现了这个错误,不知道如何解决

### ISSUE THREAD

**Issue by thereisnowinter** [finalion/WordQuery#65]
一个插件发生了错误。
请把它报告在插件的论坛上:
https://anki.tenderapp.com/discussions/add-ons

Traceback (most recent call last):
File "aqt\progress.py", line 69, in handler
File "aqt\main.py", line 110, in setupProfile
File "aqt\main.py", line 244, in loadProfile
File "anki\hooks.py", line 26, in runHook
File "C:\Users\Newman\AppData\Roaming\Anki2\addons\wordquery.py", line 31, in start_here
import wquery
File "C:\Users\Newman\AppData\Roaming\Anki2\addons\wquery\__init__.py", line 27, in <module>
from ui import show_options
File "C:\Users\Newman\AppData\Roaming\Anki2\addons\wquery\ui.py", line 34, in <module>
from wquery.service import service_manager
File "C:\Users\Newman\AppData\Roaming\Anki2\addons\wquery\service\__init__.py", line 24, in <module>
service_manager = ServiceManager()
File "C:\Users\Newman\AppData\Roaming\Anki2\addons\wquery\service\manager.py", line 36, in __init__
self.local_services = self.get_available_local_services()
File "C:\Users\Newman\AppData\Roaming\Anki2\addons\wquery\service\manager.py", line 106, in get_available_local_services
services.add(MdxService(dict_path))
File "C:\Users\Newman\AppData\Roaming\Anki2\addons\wquery\service\base.py", line 271, in __init__
self.builder.get_header()
File "C:\Users\Newman\AppData\Roaming\Anki2\addons\wquery\libs\mdict\mdict_query.py", line 69, in get_header
each[0] for each in cursor)
ValueError: need more than 2 values to unpack

**Comment by finalion** [comment]
没有升级到最新版吧？

**Comment by thereisnowinter** [comment]
@finalion 我看了一下,已经升级到最新版了,版本 2.0.48,但结果还是这样.反反复复试了很多次

**Comment by finalion** [comment]
我是说插件的最新版

**Comment by thereisnowinter** [comment]
谢谢,已经解决了.
