### ISSUE TITLE
请问bing xtk的网络词典是暂时不可用还是永久不可用了？

### ISSUE THREAD

**Issue by Tindharia** [finalion/WordQuery#68]
还有一个问题是每次打开anki后第一次用word query的时候会出现
 
Traceback (most recent call last):
  File "/Users/tindharia/Library/Application Support/Anki2/addons/wquery/query.py", line 320, in run
    result = self.query(service_field, word)
  File "/Users/tindharia/Library/Application Support/Anki2/addons/wquery/query.py", line 333, in query
    return self.service.active(service_field, word)
  File "/Users/tindharia/Library/Application Support/Anki2/addons/wquery/service/base.py", line 173, in active
    result = each[1]()
  File "/Users/tindharia/Library/Application Support/Anki2/addons/wquery/service/base.py", line 58, in _deco
    res = fld_func(cls, *args, **kwargs)
  File "/Users/tindharia/Library/Application Support/Anki2/addons/wquery/service/base.py", line 286, in fld_whole
    html = self.get_html()
  File "/Users/tindharia/Library/Application Support/Anki2/addons/wquery/service/base.py", line 300, in get_html
    html = self.adapt_to_anki(result[0])
  File "/Users/tindharia/Library/Application Support/Anki2/addons/wquery/service/base.py", line 326, in adapt_to_anki
    self.save_media_files(media_files_set)
  File "/Users/tindharia/Library/Application Support/Anki2/addons/wquery/service/base.py", line 367, in save_media_files
    keys = self.builder.get_mdd_keys(each)
  File "/Users/tindharia/Library/Application Support/Anki2/addons/wquery/libs/mdict/mdict_query.py", line 315, in get_mdd_keys
    return self.get_keys(self._mdd_db, query)
  File "/Users/tindharia/Library/Application Support/Anki2/addons/wquery/libs/mdict/mdict_query.py", line 310, in get_keys
    cursor = conn.execute(sql)
sqlite3.OperationalError: no such table: MDX_INDEX

这个错误，但是第二次以后就好了请问这是为什么？

问题较长，不好意思。

**Comment by finalion** [comment]
1. bing xtk词典是知乎上一个朋友自己做的api，刚才试了下，服务不能用了，我需要问一下他。

2. 这个问题应该是解决了，你更新下最新的这个版本试试。

**Comment by Tindharia** [comment]
感谢回复
